apiVersion: apps/v1
kind: Deployment
metadata:
  name: cold-backend
  labels:
    app: cold-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cold-backend
  template:
    metadata:
      labels:
        app: cold-backend
    spec:
      containers:
      - name: cold-backend
        image: cold-backend:latest
        imagePullPolicy: Never  # Use local image imported to k3s
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "192.168.15.131" # Host IP (since DB is on metal)
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "Lak992723/"
        - name: DB_NAME
          value: "cold_db"
        - name: REDIS_HOST
          value: "192.168.15.131"
        - name: REDIS_PORT
          value: "6379"
        - name: APP_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: cold-backend-service
spec:
  type: NodePort
  selector:
    app: cold-backend
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
